MPI=true

ifeq ($(MPI),true)
   FC=mpif77
   MPIFILE=mympi
   EXEC=afnucmatmpi
else
   FC=ifort
   MPIFILE=nompi
   EXEC=afnucmat
endif

OMP= #-openmp -lpthread -openmp-report
FFLAGS=-O3 $(OMP)
#FFLAGS=-check all -O0 -warn all
F77FLAGS=-r8
MATRIX=matrixlapack
LDFLAGS=-L$(HOME)/home/lib
#LDFLAGS=-L$(HOME)/local/lapack
LIBS=-llapackmin -lblasmin $(OMP) -check all -warn all
#LIBS=-llapack -lrefblas $(OMP) -check all -warn all
#LDFLAGS=-L$(HOME)/local/ifort11/mkl/include -L$(HOME)/local/ifort11/mkl/lib/intel64
#LIBS=-lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread $(OMP) #-check all -warn all
.SUFFIXES:
.SUFFIXES: .o .f .f90

.f90.o:
	$(FC) $(FFLAGS) -c $<

OBJECTS=\
   afnuclear.o\
   confs.o\
   estimator.o\
   jastrowtabop.o\
   kshellold.o\
   lattice.o\
   pot.o\
   ran.o\
   stack.o\
   step.o\
   v6pot.o\
   $(MATRIX).o\
   $(MPIFILE).o\
   opwave.o\
   nucma_fts.o\
   optimizer.o\
   cheft.o\
   backflow.o\
   correlator.o\
   gofr.o\
   v3bpot.o\
   euclidean.o\
   propv3.o\
   operators.o

afnuclear: $(OBJECTS)
	$(FC) $(LDFLAGS) -o ./$(EXEC) $(OBJECTS) $(LIBS)

clean:
	rm -f *\.mod *\.o *~

afnuclear.o: stack.o lattice.o ran.o estimator.o $(MPIFILE).o v6pot.o operators.o\
	jastrowtabop.o step.o opwave.o optimizer.o confs.o gofr.o v3bpot.o propv3.o euclidean.o afnuclear.f90
	$(FC) $(FFLAGS) -c afnuclear.f90

stack.o: stack.f90
	$(FC) $(FFLAGS) -c stack.f90

lattice.o: lattice.f90
	$(FC) $(FFLAGS) -c lattice.f90

ran.o: ran.f90
	$(FC) $(FFLAGS) -c ran.f90

estimator.o: $(MPIFILE).o estimator.f90
	$(FC) $(FFLAGS) -c estimator.f90

$(MPIFILE).o: $(MPIFILE).f90
	$(FC) $(FFLAGS) -c $(MPIFILE).f90

$(MATRIX).o: $(MATRIX).f90
	$(FC) $(FFLAGS) -c $(MATRIX).f90

v6pot.o: cheft.o v6pot.f90
	$(FC) $(FFLAGS) -c v6pot.f90

jastrowtabop.o: $(MPIFILE).o nucma_fts.o v3bpot.o jastrowtabop.f90
	$(FC) $(FFLAGS) -c jastrowtabop.f90

step.o: stack.o ran.o opwave.o estimator.o $(MPIFILE).o v6pot.o $(MATRIX).o gofr.o step.f90
	$(FC) $(FFLAGS) -c step.f90

opwave.o: stack.o jastrowtabop.o v6pot.o $(MATRIX).o backflow.o correlator.o v6pot.o v3bpot.o opwave.f90
	$(FC) $(FFLAGS) -c opwave.f90

pot.o: pot.f
	$(FC) $(F77FLAGS) -c pot.f

nucma_fts.o: nucma_fts.f90
	$(FC) -c nucma_fts.f90

optimizer.o: $(MPIFILE).o stack.o $(MATRIX).o optimizer.f90
	$(FC) $(FFLAGS) -c optimizer.f90

cheft.o: cheft.f90
	$(FC) $(FFLAGS) -c cheft.f90

confs.o: confs.f90
	$(FC) $(FFLAGS) -c confs.f90

backflow.o: backflow.f90
	$(FC) $(FFLAGS) -c backflow.f90

correlator.o: $(MATRIX).o v3bpot.o correlator.f90
	$(FC) $(FFLAGS) -c correlator.f90

gofr.o: stack.o opwave.o gofr.f90
	$(FC) $(FFLAGS) -c gofr.f90

v3bpot.o: v3bpot.f90
	$(FC) $(FFLAGS) -c v3bpot.f90

euclidean.o: stack.o euclidean.f90
	$(FC) $(FFLAGS) -c euclidean.f90

propv3.o: $(MPIFILE).o stack.f90 propv3.f90
	$(FC) $(FFLAGS) -c propv3.f90

operators.o: stack.o ran.o opwave.o estimator.o $(MPIFILE).o gofr.o operators.f90
	$(FC) $(FFLAGS) -c operators.f90
